connector.name=iceberg
iceberg.catalog.type=hadoop
iceberg.file-format=PARQUET

# Point Trino to the Lakehouse bucket in MinIO
hive.s3.endpoint=http://minio:9000
hive.s3.aws-access-key=admin
hive.s3.aws-secret-key=password
hive.s3.path-style-access=true

# Trino uses S3a prefix internally to read the Iceberg metadata from MinIO
fs.hadoop.fs.s3a.endpoint=http://minio:9000
fs.hadoop.fs.s3a.access.key=admin
fs.hadoop.fs.s3a.secret.key=password
fs.hadoop.fs.s3a.path.style.access=true
